num1=int(input("enter the first num"))
num2=int(input("enter the second num"))
print(num1+num2)
print(num1-num2)
print(num1/num2)
print(num1//num2)
print(num1%num2)
print(num1**num2)
num1+=2
print(num1)
